from setuptools import setup

setup(
    name='Epatient',
    version='',
    packages=['env.Lib.distutils', 'env.Lib.encodings', 'env.Lib.importlib', 'env.Lib.collections',
              'env.Lib.site-packages.pip', 'env.Lib.site-packages.pip._vendor',
              'env.Lib.site-packages.pip._vendor.idna', 'env.Lib.site-packages.pip._vendor.pep517',
              'env.Lib.site-packages.pip._vendor.pytoml', 'env.Lib.site-packages.pip._vendor.certifi',
              'env.Lib.site-packages.pip._vendor.chardet', 'env.Lib.site-packages.pip._vendor.chardet.cli',
              'env.Lib.site-packages.pip._vendor.distlib', 'env.Lib.site-packages.pip._vendor.distlib._backport',
              'env.Lib.site-packages.pip._vendor.msgpack', 'env.Lib.site-packages.pip._vendor.urllib3',
              'env.Lib.site-packages.pip._vendor.urllib3.util', 'env.Lib.site-packages.pip._vendor.urllib3.contrib',
              'env.Lib.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'env.Lib.site-packages.pip._vendor.urllib3.packages',
              'env.Lib.site-packages.pip._vendor.urllib3.packages.backports',
              'env.Lib.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'env.Lib.site-packages.pip._vendor.colorama', 'env.Lib.site-packages.pip._vendor.html5lib',
              'env.Lib.site-packages.pip._vendor.html5lib._trie', 'env.Lib.site-packages.pip._vendor.html5lib.filters',
              'env.Lib.site-packages.pip._vendor.html5lib.treewalkers',
              'env.Lib.site-packages.pip._vendor.html5lib.treeadapters',
              'env.Lib.site-packages.pip._vendor.html5lib.treebuilders', 'env.Lib.site-packages.pip._vendor.lockfile',
              'env.Lib.site-packages.pip._vendor.progress', 'env.Lib.site-packages.pip._vendor.requests',
              'env.Lib.site-packages.pip._vendor.packaging', 'env.Lib.site-packages.pip._vendor.cachecontrol',
              'env.Lib.site-packages.pip._vendor.cachecontrol.caches', 'env.Lib.site-packages.pip._vendor.webencodings',
              'env.Lib.site-packages.pip._vendor.pkg_resources', 'env.Lib.site-packages.pip._internal',
              'env.Lib.site-packages.pip._internal.cli', 'env.Lib.site-packages.pip._internal.req',
              'env.Lib.site-packages.pip._internal.vcs', 'env.Lib.site-packages.pip._internal.utils',
              'env.Lib.site-packages.pip._internal.models', 'env.Lib.site-packages.pip._internal.commands',
              'env.Lib.site-packages.pip._internal.operations', 'env.Lib.site-packages.pytz',
              'env.Lib.site-packages.wheel', 'env.Lib.site-packages.wheel.cli', 'env.Lib.site-packages.django',
              'env.Lib.site-packages.django.db', 'env.Lib.site-packages.django.db.models',
              'env.Lib.site-packages.django.db.models.sql', 'env.Lib.site-packages.django.db.models.fields',
              'env.Lib.site-packages.django.db.models.functions', 'env.Lib.site-packages.django.db.backends',
              'env.Lib.site-packages.django.db.backends.base', 'env.Lib.site-packages.django.db.backends.dummy',
              'env.Lib.site-packages.django.db.backends.mysql', 'env.Lib.site-packages.django.db.backends.oracle',
              'env.Lib.site-packages.django.db.backends.sqlite3', 'env.Lib.site-packages.django.db.backends.postgresql',
              'env.Lib.site-packages.django.db.backends.postgresql_psycopg2',
              'env.Lib.site-packages.django.db.migrations', 'env.Lib.site-packages.django.db.migrations.operations',
              'env.Lib.site-packages.django.apps', 'env.Lib.site-packages.django.conf',
              'env.Lib.site-packages.django.conf.urls', 'env.Lib.site-packages.django.conf.locale',
              'env.Lib.site-packages.django.conf.locale.ar', 'env.Lib.site-packages.django.conf.locale.az',
              'env.Lib.site-packages.django.conf.locale.bg', 'env.Lib.site-packages.django.conf.locale.bn',
              'env.Lib.site-packages.django.conf.locale.bs', 'env.Lib.site-packages.django.conf.locale.ca',
              'env.Lib.site-packages.django.conf.locale.cs', 'env.Lib.site-packages.django.conf.locale.cy',
              'env.Lib.site-packages.django.conf.locale.da', 'env.Lib.site-packages.django.conf.locale.de',
              'env.Lib.site-packages.django.conf.locale.el', 'env.Lib.site-packages.django.conf.locale.en',
              'env.Lib.site-packages.django.conf.locale.eo', 'env.Lib.site-packages.django.conf.locale.es',
              'env.Lib.site-packages.django.conf.locale.et', 'env.Lib.site-packages.django.conf.locale.eu',
              'env.Lib.site-packages.django.conf.locale.fa', 'env.Lib.site-packages.django.conf.locale.fi',
              'env.Lib.site-packages.django.conf.locale.fr', 'env.Lib.site-packages.django.conf.locale.fy',
              'env.Lib.site-packages.django.conf.locale.ga', 'env.Lib.site-packages.django.conf.locale.gd',
              'env.Lib.site-packages.django.conf.locale.gl', 'env.Lib.site-packages.django.conf.locale.he',
              'env.Lib.site-packages.django.conf.locale.hi', 'env.Lib.site-packages.django.conf.locale.hr',
              'env.Lib.site-packages.django.conf.locale.hu', 'env.Lib.site-packages.django.conf.locale.id',
              'env.Lib.site-packages.django.conf.locale.is', 'env.Lib.site-packages.django.conf.locale.it',
              'env.Lib.site-packages.django.conf.locale.ja', 'env.Lib.site-packages.django.conf.locale.ka',
              'env.Lib.site-packages.django.conf.locale.km', 'env.Lib.site-packages.django.conf.locale.kn',
              'env.Lib.site-packages.django.conf.locale.ko', 'env.Lib.site-packages.django.conf.locale.lt',
              'env.Lib.site-packages.django.conf.locale.lv', 'env.Lib.site-packages.django.conf.locale.mk',
              'env.Lib.site-packages.django.conf.locale.ml', 'env.Lib.site-packages.django.conf.locale.mn',
              'env.Lib.site-packages.django.conf.locale.nb', 'env.Lib.site-packages.django.conf.locale.nl',
              'env.Lib.site-packages.django.conf.locale.nn', 'env.Lib.site-packages.django.conf.locale.pl',
              'env.Lib.site-packages.django.conf.locale.pt', 'env.Lib.site-packages.django.conf.locale.ro',
              'env.Lib.site-packages.django.conf.locale.ru', 'env.Lib.site-packages.django.conf.locale.sk',
              'env.Lib.site-packages.django.conf.locale.sl', 'env.Lib.site-packages.django.conf.locale.sq',
              'env.Lib.site-packages.django.conf.locale.sr', 'env.Lib.site-packages.django.conf.locale.sv',
              'env.Lib.site-packages.django.conf.locale.ta', 'env.Lib.site-packages.django.conf.locale.te',
              'env.Lib.site-packages.django.conf.locale.th', 'env.Lib.site-packages.django.conf.locale.tr',
              'env.Lib.site-packages.django.conf.locale.uk', 'env.Lib.site-packages.django.conf.locale.vi',
              'env.Lib.site-packages.django.conf.locale.de_CH', 'env.Lib.site-packages.django.conf.locale.en_AU',
              'env.Lib.site-packages.django.conf.locale.en_GB', 'env.Lib.site-packages.django.conf.locale.es_AR',
              'env.Lib.site-packages.django.conf.locale.es_CO', 'env.Lib.site-packages.django.conf.locale.es_MX',
              'env.Lib.site-packages.django.conf.locale.es_NI', 'env.Lib.site-packages.django.conf.locale.es_PR',
              'env.Lib.site-packages.django.conf.locale.pt_BR', 'env.Lib.site-packages.django.conf.locale.sr_Latn',
              'env.Lib.site-packages.django.conf.locale.zh_Hans', 'env.Lib.site-packages.django.conf.locale.zh_Hant',
              'env.Lib.site-packages.django.core', 'env.Lib.site-packages.django.core.mail',
              'env.Lib.site-packages.django.core.mail.backends', 'env.Lib.site-packages.django.core.cache',
              'env.Lib.site-packages.django.core.cache.backends', 'env.Lib.site-packages.django.core.files',
              'env.Lib.site-packages.django.core.checks', 'env.Lib.site-packages.django.core.checks.security',
              'env.Lib.site-packages.django.core.checks.compatibility', 'env.Lib.site-packages.django.core.servers',
              'env.Lib.site-packages.django.core.handlers', 'env.Lib.site-packages.django.core.management',
              'env.Lib.site-packages.django.core.serializers', 'env.Lib.site-packages.django.http',
              'env.Lib.site-packages.django.test', 'env.Lib.site-packages.django.urls',
              'env.Lib.site-packages.django.forms', 'env.Lib.site-packages.django.utils',
              'env.Lib.site-packages.django.utils.translation', 'env.Lib.site-packages.django.views',
              'env.Lib.site-packages.django.views.generic', 'env.Lib.site-packages.django.views.decorators',
              'env.Lib.site-packages.django.contrib', 'env.Lib.site-packages.django.contrib.gis',
              'env.Lib.site-packages.django.contrib.gis.db', 'env.Lib.site-packages.django.contrib.gis.db.models',
              'env.Lib.site-packages.django.contrib.gis.db.models.sql',
              'env.Lib.site-packages.django.contrib.gis.db.backends',
              'env.Lib.site-packages.django.contrib.gis.db.backends.base',
              'env.Lib.site-packages.django.contrib.gis.db.backends.mysql',
              'env.Lib.site-packages.django.contrib.gis.db.backends.oracle',
              'env.Lib.site-packages.django.contrib.gis.db.backends.postgis',
              'env.Lib.site-packages.django.contrib.gis.db.backends.spatialite',
              'env.Lib.site-packages.django.contrib.gis.gdal', 'env.Lib.site-packages.django.contrib.gis.gdal.raster',
              'env.Lib.site-packages.django.contrib.gis.gdal.prototypes',
              'env.Lib.site-packages.django.contrib.gis.geos',
              'env.Lib.site-packages.django.contrib.gis.geos.prototypes',
              'env.Lib.site-packages.django.contrib.gis.admin', 'env.Lib.site-packages.django.contrib.gis.forms',
              'env.Lib.site-packages.django.contrib.gis.utils', 'env.Lib.site-packages.django.contrib.gis.geoip2',
              'env.Lib.site-packages.django.contrib.gis.sitemaps',
              'env.Lib.site-packages.django.contrib.gis.serializers', 'env.Lib.site-packages.django.contrib.auth',
              'env.Lib.site-packages.django.contrib.auth.handlers',
              'env.Lib.site-packages.django.contrib.auth.management',
              'env.Lib.site-packages.django.contrib.auth.migrations', 'env.Lib.site-packages.django.contrib.admin',
              'env.Lib.site-packages.django.contrib.admin.views',
              'env.Lib.site-packages.django.contrib.admin.migrations',
              'env.Lib.site-packages.django.contrib.admin.templatetags', 'env.Lib.site-packages.django.contrib.sites',
              'env.Lib.site-packages.django.contrib.sites.migrations', 'env.Lib.site-packages.django.contrib.humanize',
              'env.Lib.site-packages.django.contrib.humanize.templatetags',
              'env.Lib.site-packages.django.contrib.messages', 'env.Lib.site-packages.django.contrib.messages.storage',
              'env.Lib.site-packages.django.contrib.postgres', 'env.Lib.site-packages.django.contrib.postgres.forms',
              'env.Lib.site-packages.django.contrib.postgres.fields',
              'env.Lib.site-packages.django.contrib.postgres.aggregates',
              'env.Lib.site-packages.django.contrib.sessions', 'env.Lib.site-packages.django.contrib.sessions.backends',
              'env.Lib.site-packages.django.contrib.sessions.migrations',
              'env.Lib.site-packages.django.contrib.sitemaps', 'env.Lib.site-packages.django.contrib.admindocs',
              'env.Lib.site-packages.django.contrib.flatpages',
              'env.Lib.site-packages.django.contrib.flatpages.migrations',
              'env.Lib.site-packages.django.contrib.flatpages.templatetags',
              'env.Lib.site-packages.django.contrib.redirects',
              'env.Lib.site-packages.django.contrib.redirects.migrations',
              'env.Lib.site-packages.django.contrib.staticfiles',
              'env.Lib.site-packages.django.contrib.staticfiles.templatetags',
              'env.Lib.site-packages.django.contrib.syndication', 'env.Lib.site-packages.django.contrib.contenttypes',
              'env.Lib.site-packages.django.contrib.contenttypes.management',
              'env.Lib.site-packages.django.contrib.contenttypes.migrations', 'env.Lib.site-packages.django.dispatch',
              'env.Lib.site-packages.django.template', 'env.Lib.site-packages.django.template.loaders',
              'env.Lib.site-packages.django.template.backends', 'env.Lib.site-packages.django.middleware',
              'env.Lib.site-packages.django.templatetags', 'env.Lib.site-packages.setuptools',
              'env.Lib.site-packages.setuptools.extern', 'env.Lib.site-packages.setuptools._vendor',
              'env.Lib.site-packages.setuptools._vendor.packaging', 'env.Lib.site-packages.setuptools.command',
              'env.Lib.site-packages.pkg_resources', 'env.Lib.site-packages.pkg_resources.extern',
              'env.Lib.site-packages.pkg_resources._vendor', 'env.Lib.site-packages.pkg_resources._vendor.packaging',
              'main', 'main.migrations', 'accounts', 'accounts.migrations'],
    url='',
    license='',
    author='RHH GO!',
    author_email='',
    description=''
)
